### ISSUE TITLE
Building error - slualibs.h

### ISSUE THREAD

**Issue by milisarge** [philanc/slua#2]
hi, i building slua with musl-gcc but it gives:
```
musl-gcc -c -Os -Isrc/lua-5.4.2/src  -DLUA_USE_LINUX  src/lua-5.4.2/src/*.c
musl-gcc -c -Os -Isrc/lua-5.4.2/src  -DLUA_USE_LINUX src/l5.c src/linenoise.c 
musl-gcc -c -Os -Isrc/lua-5.4.2/src  -DLUA_USE_LINUX -DBASE64 -DLZMA -DBLAKE -DX25519 -DMORUS src/luazen-0.16/*.c
musl-gcc -c -Os -Isrc/lua-5.4.2/src  -DLUA_USE_LINUX  -D_7ZIP_ST src/luazen-0.16/lzma/*.c
ar rcu slua.a *.o
musl-gcc -static -o slua -Os -Isrc/lua-5.4.2/src  -DLUA_USE_LINUX  src/slua.c slua.a
src/slua.c: In function 'pmain':
src/slua.c:610:10: fatal error: slualibs.h: No such file or directory
  610 | #include "slualibs.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:109: slua] Error 1
```
i could not even find slualibs.h in repo.

**Comment by milisarge** [comment]
i think it is obsolete, just commented it and built successfully..

**Comment by philanc** [comment]
Hi Milisarge,

Thanks for the report. I forgot to git add slualibs.h  so it did build/work only on my PC - silly me!

Sorry for the trouble.  It should be fixed with the last commit.  `#include slualibs.h` is needed in order to build slua with the additional libraries.

Hope it works now for you. 

Phil

**Comment by milisarge** [comment]
it built it with addtional libraries without problem - thnks much
